-- Destroys all data.

DROP TRIGGER IF EXISTS afterRecipeDeleteTrigger ON Recipe;
DROP TRIGGER IF EXISTS afterItemUpdateTrigger ON Item;

DROP TABLE IF EXISTS RecipeRequirement;
DROP TABLE IF EXISTS RecipeStep;
DROP TABLE IF EXISTS Recipe;
DROP TABLE IF EXISTS ItemOrder;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS AppUser;

DROP FUNCTION IF EXISTS afterRecipeDelete();
DROP FUNCTION IF EXISTS afterItemUpdate();
DROP FUNCTION IF EXISTS verifyItemOwner(INTEGER);
DROP FUNCTION IF EXISTS uniqRecipeRequirement(INTEGER, TEXT);

DROP TYPE IF EXISTS UserType;